name: CI

on:
  push:
    branches: [ main ]

jobs:
  gitpage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: build
        run: |
          npm ci
          npx ng add angular-cli-ghpages
          npx ng deploy --base-href=/${{ github.event.repository.name }}/ --skip-confirmation
      - name: commit and push
        run: |
          cd dist/manzy.io/browser
          git init
          git config user.name  "build-ci"
          git config user.email "build-ci@github.com"
          git remote add secure-origin https://${{ secrets.general_ci }}@github.com/ksw2000/${{ github.event.repository.name }}
          git checkout -b gh-pages
          git add .
          git commit -m "gitpage by CI"
          git push --force secure-origin gh-pages